# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Backend import Backend
from PyQt5.QtWidgets import QApplication, QMainWindow, QProgressBar, QWidget, QVBoxLayout
from PyQt5.QtCore import Qt, QRectF
from PyQt5.QtGui import QPainter, QColor

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.backend = Backend(self)
        MainWindow.setObjectName("Dementia Detection")
        MainWindow.resize(1024, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        
        self.Button_select_video = QtWidgets.QPushButton(self.centralwidget)
        pixmap = QtGui.QPixmap("./UI/select_button.png")
        self.Button_select_video.setGeometry(QtCore.QRect(320, 80, 400, 400))
        self.Button_select_video.setIcon(QtGui.QIcon(pixmap))
        self.Button_select_video.setIconSize(QtCore.QSize(400, 400))
        self.Button_select_video.setObjectName("Button_select_video")
        self.Button_select_video.clicked.connect(self.backend.load_video)
        self.Button_select_video.setStyleSheet("background-color: transparent;")
        # self.Button_select_video.hide()
        
        self.label_select_video = QtWidgets.QLabel(self.centralwidget)
        self.label_select_video.setGeometry(QtCore.QRect(430, 450, 700, 100))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(25)
        font.setBold(True)
        self.label_select_video.setFont(font)
        self.label_select_video.setObjectName("label_select_video")
        self.label_select_video.setText(" 選擇影片")
        # self.label_select_video.hide()
        
        self.Button_start_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start_analyze.setGeometry(QtCore.QRect(370, 620, 300, 80))
        self.Button_start_analyze.setStyleSheet("QPushButton{\n"
        "        border-radius: 40px;\n"
        "        background-color: rgb(166, 166, 166);\n"
        "        font:  20pt \"微軟正黑體\"; \n"
        "}\n"
        )
        self.Button_start_analyze.setObjectName("Button_start_analyze")
        self.Button_start_analyze.clicked.connect(self.backend.start_analysis)
        self.Button_start_analyze.setEnabled(False)
        # self.Button_start_analyze.hide()
        
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(330, 100, 700, 100))
        self.label_status.setStyleSheet("font:  40pt \"Courier New\"; ")
        self.label_status.setObjectName("label_stastus")
        self.label_status.hide()
        
        self.label_loading = QtWidgets.QLabel(self.centralwidget)
        self.label_loading.setGeometry(QtCore.QRect(350, 550, 700, 100))
        self.label_loading.setStyleSheet("font:  40pt \"Courier New\"; ")
        self.label_loading.setObjectName("label_loading")
        self.label_loading.hide()
        
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(170, 270, 700, 200))
        self.progress_bar.setObjectName("progress_bar")
        self.progress_bar.setStyleSheet("QProgressBar{"
                                        "border : 3px  solid #000000;"
                                        "background : transparent;"
                                        "text-align : center;"
                                        "color : rgb(255,255,255);"
                                    "}"
                                    "QProgressBar::chunk{"
                                        "background-color :rgb(0,0,0);"
                                        "width: 29.5px;"
                                        "margin: 0.5px;"
                                    "}")
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setValue(0)
        self.progress_bar.hide()
        

        self.label_predict_CDR = QtWidgets.QLabel(self.centralwidget)
        self.label_predict_CDR.setGeometry(QtCore.QRect(180, 200, 700, 100))
        self.label_predict_CDR.setStyleSheet("font:  40pt \"微軟正黑體\"; ")
        self.label_predict_CDR.setObjectName("label_predict_CDR")
        # self.label_predict_CDR.setText("程式分析預測結果")
        self.label_predict_CDR.hide()

        self.label_origin_CDR = QtWidgets.QLabel(self.centralwidget)
        self.label_origin_CDR.setGeometry(QtCore.QRect(350, 320, 700, 100))
        self.label_origin_CDR.setStyleSheet("font:  20pt \"微軟正黑體\"; ")
        self.label_origin_CDR.setObjectName("label_origin_CDR")
        # self.label_origin_CDR.setText("醫院分析預測結果")
        self.label_origin_CDR.hide()
        
        self.label_show_save = QtWidgets.QLabel(self.centralwidget)
        self.label_show_save.setGeometry(QtCore.QRect(300, 700, 600, 60))
        self.label_show_save.setStyleSheet("font:  20pt \"微軟正黑體\";  ")
        self.label_show_save.setObjectName("label_show_save")
        # self.label_show_save.setText("分析結果已儲存")
        self.label_show_save.hide()
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基於音訊與視訊失智症檢測系統"))
        self.Button_start_analyze.setText(_translate("MainWindow", "開始分析"))


